HighTeach/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as users


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePage, name='homePage'),
    path('course/', include('course.urls')),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/homePage.html'), name='logout'),
    path('study-group/', include('study_group.urls')),
    path('course/', include('course.urls')),
    path('feed/', include('feed.urls')),
    path('chat/', include('chat.urls')),
    path('register/', users.register, name='signup'),
    path('users/', include('users.urls')),
    path('main/', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from chat import views


urlpatterns = [
    path('', views.chat_view, name='chat'),
    path('courses/<int:course_id>', views.getCourseChat),
    path('groups/<int:group_id>', views.getGroupChat),
    path('post-message/', views.addMessage),
]

course/urls.py
from django.urls import path
from .views import CourseList, AddCourse, CoursePage, ConnectCourseToStudent, AcceptOrDeclineStudentCourse
from course import views


urlpatterns = [
    path('<int:course_id>/add_review', views.CreateReviewView.as_view(), name="add_review"),
    path('<int:course_id>/delete_review', views.DeleteReviewView.as_view(), name="delete_review"),
    path('<int:course_id>/update_review', views.UpdateReviewView.as_view(), name="update_review"),
    path('', CourseList.as_view(), name='show_courses'),
    path('add', AddCourse.as_view(), name="add_course"),
    path('<int:course_id>', CoursePage.as_view(), name="coursePage"),
    path('<int:course_id>/connect', ConnectCourseToStudent.as_view(), name="connect"),
    path('<int:course_id>/<int:student_course_id>', AcceptOrDeclineStudentCourse.as_view(),
         name="accept_decline_request"),
]

course/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError

Category = [
    ('BUSINESS_AND_MANAGEMENT', 'Business & Management'),
    ('COMPUTER_SCIENCE_AND_IT', 'Computer Science & IT'),
    ('CREATIVE_ARTS', 'Creative Arts'),
    ('ECONOMICS', 'Economics'),
    ('HISTORY', 'History'),
    ('HEALTH_AND_PSYCHOLOGY', 'Health & Psychology'),
    ('LITERATURE', 'Literature'),
    ('LAW', 'Law'),
    ('LANGUAGES_AND_CULTURES', 'Languages & Cultures'),
    ('MATHS', 'Maths'),
    ('MARKETING', 'Marketing'),
    ('OTHER', 'Other'),
    ('POLITICS_AND_SOCIETY', 'Politics & Society'),
    ('SCIENCE_AND_ENGINEERING', 'Science & Engineering'),
    ('SPORT_AND_LEISURE', 'Sport & Leisure'),
]

Level = [
    ('B', 'Beginner'),
    ('I', 'Intermediate'),
    ('A', 'Advanced'),
]


class TeacherCourseManager(models.Manager):

    def in_price_range(self, min: int, max: int):
        return self.filter(price__lte=max, price__gte=min)

    def in_category(self, cat: str):
        return self.filter(category=cat)

    def got_experience(self, exp: int):
        if exp > 5:
            exp = 5
        return self.filter(years_of_experience__gte=exp)

    def search_name(self, keyword: str):
        return self.filter(Q(course_name__icontains=keyword) | Q(description__icontains=keyword))

    def get_level(self, level: str):
        return self.filter(difficulty_level=level)

    def get_teacher_courses(self, id: int):
        return self.filter(teacher_id=id)

    def get_student_approved_teacher_courses(self, id: User):
        teacher_courses = self.none()
        studentCourses = StudentCourse.objects.get_student_confirmed(id=id)
        for student in studentCourses.values_list():
            teacher_courses |= self.filter(course_id=student[2])
        return teacher_courses


class TeacherCourse(models.Model):
    course_id = models.BigAutoField(primary_key=True)
    teacher_id = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=30, blank=False)
    description = models.TextField()
    price = models.PositiveIntegerField(default=0, blank=False)
    objects = TeacherCourseManager()

    class Experience(models.IntegerChoices):
        ZERO = 0, _("0")
        ONE = 1, _("1")
        TWO = 2, _("2")
        THREE = 3, _("3")
        FOUR = 4, _("4")
        FIVE_PLUS = 5, _("5+")

    years_of_experience = models.IntegerField(
        choices=Experience.choices,
        default=Experience.ZERO
    )

    difficulty_level = models.CharField(
        max_length=30,
        choices=Level,
    )

    category = models.CharField(
        max_length=30,
        choices=Category,
    )

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

    def get_experience(self):
        # Function for display in Admin
        return self.Experience.choices[int(self.years_of_experience)][1]

    def is_student_in_course(self, student: User):
        if StudentCourse.objects.is_student_enrolled_in_course(self, student):
            return 'C'
        if StudentCourse.objects.is_student_requset_pending(self, student):
            return 'P'
        if StudentCourse.objects.is_student_request_declined(self, student):
            return 'D'
        return 'N'

    def get_pending_requset_count_for_course(self):
        return StudentCourse.objects.get_course_students_pending_requset(self).count()

    def avg_rating_for_course(self):
        avg = Review.objects.get_avg_rating_by_course(self)
        if avg is None:
            return 0
        return '%.2f' % avg

    def __str__(self):
        return self.course_name

    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Teacher Courses"


class ReviewManager(models.Manager):

    def get_reviews_by_course(self, course: TeacherCourse):
        reviews = Review.objects.filter(course=course)
        return reviews

    def get_avg_rating_by_course(self, course: TeacherCourse):
        avg_rating = self.filter(course=course).aggregate(models.Avg('rating'))['rating__avg']
        return avg_rating

    def get_number_of_review_of_course(self, course: TeacherCourse):
        return len(self.filter(course=course))

    def check_if_review_exist_by_student(self, student: User, course: TeacherCourse):
        reviews_by_course = self.get_reviews_by_course(course)
        try:
            return reviews_by_course.get(student=student)
        except Review.DoesNotExist:
            return None

    def get_review_in_course_by_student(self, student: User, course: TeacherCourse):
        reviews_by_course = self.get_reviews_by_course(course)
        return reviews_by_course.get(student=student)


class Review(models.Model):
    review_id = models.BigAutoField(primary_key=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(TeacherCourse, on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    content = models.TextField(blank=True)
    date = models.DateField(auto_now_add=True)
    objects = ReviewManager()


class StudentCourseManager(models.Manager):

    def get_teacher_pending(self, id: int):
        return TeacherCourse.objects.get_teacher_courses(id).values("course_id").intersection(
            self.filter(status=Status.PENDING).values("teacher_course_id")).values_list(flat=True)

    def get_student_pending(self, id: int):
        return self.filter(student_id=id, status=Status.PENDING)

    def get_student_courses(self, id: int):
        return self.filter(student_id=id)

    def get_student_confirmed(self, id: User):
        return self.filter(student_id=id, status=Status.CONFIRMED)

    def is_student_request_declined(self, course: TeacherCourse, student: User):
        return bool(self.filter(teacher_course_id=course, student_id=student, status=Status.REJECTED))

    def is_student_enrolled_in_course(self, course: TeacherCourse, student: User):
        return bool(self.filter(teacher_course_id=course, student_id=student, status=Status.CONFIRMED))

    def is_student_requset_pending(self, course: TeacherCourse, student: User):
        return bool(self.filter(teacher_course_id=course, student_id=student, status=Status.PENDING))

    def get_course(self, course_id: int):
        return self.filter(student_course_id=course_id)

    def get_student_courses_by_teacher(self, teacher_id: User):
        return self.filter(teacher_course_id__teacher_id=teacher_id)

    def get_course_students_pending_requset(self, course: TeacherCourse):
        return self.filter(teacher_course_id=course, status=Status.PENDING)


class Status(models.TextChoices):
    PENDING = 'Pending'
    CONFIRMED = 'Confirmed'
    REJECTED = 'Rejected'


class StudentCourse(models.Model):
    student_course_id = models.BigAutoField(primary_key=True)
    student_id = models.ForeignKey(User, on_delete=models.CASCADE)
    teacher_course_id = models.ForeignKey(TeacherCourse, on_delete=models.CASCADE)
    request_date = models.DateTimeField(auto_now_add=True)
    objects = StudentCourseManager()

    status = models.CharField(
        max_length=30,
        choices=Status.choices,
        default=Status.PENDING,
    )

    def change_to_confirmed(self):
        self.status = Status.CONFIRMED.value
        self.save()

    def change_to_rejected(self):
        self.status = Status.REJECTED.value
        self.save()

    def clean(self):
        if self.teacher_course_id.teacher_id == self.student_id:
            raise ValidationError({'teacher_course_id': "Can't create a request to your own course"})

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

    def __str__(self):
        return str(self.student_course_id)

    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Student Courses"
        constraints = [models.UniqueConstraint(fields=['student_id', 'teacher_course_id'],
                                               name="Already have a pending/confirmed request in this course")]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator


class MyUserManager(BaseUserManager):

    def create_user(self, email, username, first_name, last_name, phone_number, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")
        if not first_name:
            raise ValueError("Users must have an first name")
        if not last_name:
            raise ValueError("Users must have an last name")
        if not phone_number:
            raise ValueError("Users must have an phone number")

        user = self.model(
                email=self.normalize_email(email),
                username=username,
                first_name=first_name,
                last_name=last_name,
                phone_number=phone_number,
            )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, phone_number, password):
        user = self.create_user(
                email=self.normalize_email(email),
                password=password,
                username=username,
                first_name=first_name,
                last_name=last_name,
                phone_number=phone_number,
            )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    class Account_type(models.TextChoices):
        TEACHER = 'T', _('Teacher')
        STUDENT = 'S', _('Student')
        BOTH = 'B', _('Teacher and Student')

    class Meeting_method (models.TextChoices):
        LIVE = 'L', _('Live')
        ONLINE = 'O', _('Online')
        BOTH = 'B', _('Live and Online')

    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    user_id = models.BigAutoField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_regex = RegexValidator(regex=r'^\+?0?\d{9,15}$',
                                 message="Phone number must be entered in the format:"
                                 + "'+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    city = models.CharField(max_length=30)
    account_type = models.CharField(
        max_length=1,
        choices=Account_type.choices,
        default=Account_type.STUDENT,
        )
    meeting_method = models.CharField(
        max_length=1,
        choices=Meeting_method.choices,
        default=Meeting_method.BOTH,
        )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'phone_number',]
    objects = MyUserManager()

    def _str_(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

course/forms.py
from django import forms
from django.forms import ModelForm
from .models import TeacherCourse, Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'content']
        widgets = {
            'rating': forms.RadioSelect(attrs={'class': 'star-rating'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'style': 'resize: none'}),
        }


class TeacherCourseForm(ModelForm):
    class Meta:
        model = TeacherCourse
        fields = ('course_name', 'description',
                  'price', 'years_of_experience', 'difficulty_level',
                  'category')

course/templates/course/add_course.html
{% extends 'main/loggedInPage.html' %}
{% block main_content %}
{% load static %}
    <head>
        <title>Course</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'styles/course.add.css' %}" type="text/css">
    </head>
    
    <body>
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card mt-2 mx-auto p-4 bg-light">
                    <div class="card-body bg-light">
                        <div class="container">
                            <div class="col-md-10">
                                <h1>Add Course</h1>
                                <br>
                                <form action="" method="post">
                                    <table>
                                        {% csrf_token %}
                                        {{form}}
                                    </table>
                                    <br>
                                    <input type="submit" value="Submit" class="btn btn-success">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mx-auto">
            <img src="{% static 'images/teacher.jpg'%}" alt="teacher" class="teacher-image">
            </div>
        </div>
    </body>

{% endblock %}

course/templates/course/course_page.html
{% extends 'main/loggedInPage.html' %}
{% block main_content %}
{% load static %}

  <head>
      <title>Course</title>
      <link rel="stylesheet" href="{% static 'styles/mdb.min.css' %}" />
      <link rel="stylesheet" href="{% static 'styles/course.page.css' %}" type="text/css">
      <link rel="stylesheet" type="text/css" href="{% static 'styles/style_review.css' %}">
  </head>

  <body>
      <div class="row">
        <div class="col-2">
          <div
            class="nav flex-column nav-pills text-center"
            id="v-pills-tab"
            role="tablist"
            aria-orientation="vertical"
          >
            <a
              class="nav-link active"
              id="v-pills-course_info-tab"
              data-mdb-toggle="pill"
              href="#v-pills-course_info"
              role="tab"
              aria-controls="v-pills-course_info"
              aria-selected="true"
              >Course Info</a
            >

            {% if course.teacher_id == user %}
            <a
              class="nav-link"
              id="v-pills-requsets-tab"
              data-mdb-toggle="pill"
              href="#v-pills-requsets"
              role="tab"
              aria-controls="v-pills-requsets"
              aria-selected="false"
              >Requsets to join</a
            >
            {% endif %}
          </div>
        </div>

        <div class="col-6">
          <div class="tab-content" id="v-pills-tabContent">
            <div
              class="tab-pane fade show active"
              id="v-pills-course_info"
              role="tabpanel"
              aria-labelledby="v-pills-course_info-tab"
            >

              <label class="label">Course Name :</label>
              <p class='course_name'style="display:inline" >{{course.course_name.capitalize }}</p>

              <br></br>
              <label class="label">Course Description :</label>
              <p style="display:inline" >{{course.description}}</p>

              <br></br>
              <label class="label">Category :</label>
              <p style="display:inline">{{course.get_category_display}}</p>

              <br></br>
              <label class="label">Difficulty Level :</label>
              <p style="display:inline">{{course.get_difficulty_level_display}}</p>
            </div>

            {% if course.teacher_id == user %}
            <div
              class="tab-pane fade"
              id="v-pills-requsets"
              role="tabpanel"
              aria-labelledby="v-pills-requsets-tab"
            >
              {% block Messages %} 
              {% include "student_course.html" %}
              {% endblock %}
            </div>
            {% endif %}
          </div>
        </div>

        <div class="col-4">
              <div class="row d-flex justify-content-end align-items-flex-start h-100">
                  <div class="card" style="border-radius: 15px;">
                    <div class="card-body text-center">
                      <div class="mt-3 mb-4">
                        <div class="image">
                          {% if user.profile.image %}
                              <img src="{{ user.profile.image }}" alt="Profile Picture" 
                              class="rounded-circle img-fluid" style="width: 100px;">
                          {% else %}
                              <img src="{% static 'images/blank_profile.png' %}" alt="Profile Picture" 
                              class="rounded-circle img-fluid" style="width: 100px;">
                          {% endif %}
                        </div>
                      </div>
                      <h4 class="mb-2"><a href="/teacher">{{course.teacher_id}}</a></h4>
                      <p class="text-muted mb-4">@{{course.teacher_id.profile.profession}} </p>
                      <div class="mb-4 pb-2">
                        <button type="button" class="btn btn-outline-primary btn-floating">
                          <i class="fab fa-facebook-f fa-lg"></i>
                        </button>
                        <button type="button" class="btn btn-outline-primary btn-floating">
                          <i class="fab fa-twitter fa-lg"></i>
                        </button>
                        <button type="button" class="btn btn-outline-primary btn-floating">
                          <i class="fab fa-skype fa-lg"></i>
                        </button>
                      </div>
                      <form action='{{course.course_id}}/connect' method='POST'>
                        {% csrf_token %}
                        {% if view == 'P' %}
                        <button type='submit' class="btn btn-primary btn-rounded btn-lg" disabled>
                          Requset Sent
                        </button>
                        {% elif view == 'C' %}
                        <button type='submit' class="btn btn-primary btn-rounded btn-lg" disabled>
                          Signed-up
                        </button>
                        {% elif view == 'D' %}
                        <button type='submit' class="btn btn-primary btn-rounded btn-lg" disabled>
                          Requset Declined
                        </button>
                        {% elif course.teacher_id == user %}
                        {% else %}
                        <button type='submit' class="btn btn-primary btn-rounded btn-lg">
                          Join Course
                        </button>
                        {% endif %}

                      </form>
                      <div class="d-flex justify-content-between text-center mt-5 mb-2">
                        <div>
                          <p class="mb-2 h6">{{course.teacher_id.profile.get_meeting_method_display}}</p>
                          <p class="text-muted mb-0">Meeting Method</p>
                        </div>
                        <div class="px-3">
                          <p class="mb-2 h6">{{course.get_years_of_experience_display}}</p>
                          <p class="text-muted mb-0">Years Of Experience</p>
                        </div>
                        <div>
                          <p class="mb-2 h6">{{course.price}} ₪</p>
                          <p class="text-muted mb-0">Coruse Price</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
        </div>
      </div>
    </div>
  <hr>
  <br>

  <div class="container">
    <div class="row">
      <div class="col-3 px-md-5">
        <h5> Course Reviews :</h5>
        <br><br>
        <h7> Number Of Reviews : {{reviews.count}}</h7>
        <br><br>
        <h7> Avrage Rating : {{course.avg_rating_for_course}} / 5</h7>
        <br><br>
        {% if user != course.teacher_id %}
            {% if review_view %}
                    <button type="button" class="btn btn-primary btn-rounded btn-lg" onclick="toggleReviewForm()">Update Review</button>
                <br><br>
                <form action='{{course.course_id}}/delete_review' method="POST">
                {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-rounded btn-lg">Delete Review</button>
                </form>
            {% else %}
                    <button type="button" class="btn btn-primary btn-rounded btn-lg" onclick="toggleReviewForm()">Add Review</button>
            {% endif %}
        {% endif %}
      </div>

    {% if  messages%}
        <div id="reviewFormContainer" class="col-5">
    {% else %}
        <div id="reviewFormContainer" class="col-5" style="display: none;">
    {% endif %}
        <div class="col-5">
        {% if review_view %}
            <form action="{{course.course_id}}/update_review" method="post">
        {% else %}
            <form action="{{course.course_id}}/add_review" method="post">
        {% endif %}
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_rating">Rating:</label>
                    <div class="star-rating">
                    {% if form.rating.value %}
                        {% with form.rating.value|add:'0' as rating_value %}
                        {% for i in "54321" %}
                            {% if rating_value|stringformat:"s" == i %}
                                <input type="radio" name="{{ form.rating.name }}" id="rating-{{ i }}" value="{{ i }}" checked>
                            {% else %}
                                <input type="radio" name="{{ form.rating.name }}" id="rating-{{ i }}" value="{{ i }}">
                            {% endif %}
                            <label for="rating-{{ i }}">&#9733;</label>
                        {% endfor %}
                        {% endwith %}
                    {% else %}
                        {% for i in "54321" %}
                            <input type="radio" name="{{ form.rating.name }}" id="rating-{{ i }}" value="{{ i }}">
                            <label for="rating-{{ i }}">&#9733;</label>
                        {% endfor %}
                    {% endif %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_content" class="col-md-1.5 col-form-label">Content:</label>
                    <div class="col-md-10">
                        {{ form.content }}
                    </div>
                </div>
                <div class="form-group" style="margin-top: 30px;">
                    <div class="row">
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-primary">Submit Review</button>
                        </div>
                    </div>
                </div>
                {% if messages %}
                    <div class="alert alert-danger mt-3">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
        </div>
      </div>

      {% if reviews%}
      <div class="col-4">
        <div id="carouselExampleControls" class="carousel slide text-center carousel-dark" data-mdb-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                <h5 class="mb-3">{{reviews.first.student.username}}</h5>
                <p>{{reviews.first.student.profile.profession}}</p>
                <p class="text-muted">
                  {{reviews.first.content}}
                </p>
                </div>
              </div>
            <ul class="list-unstyled d-flex justify-content-center text-warning mb-0">
              {% with ''|center:reviews.first.rating as range %}
              {% for i in range %}
              <li><i class="fas fa-star fa-sm"></i></li>
              {% endfor %}
              {% endwith %}
            </ul>
          </div>
          {% for review in reviews %}
            {% if review != reviews.first%}
              <div class="carousel-item">
                  <div class="row d-flex justify-content-center">
                    <div class="col-lg-8">
                      <h5 class="mb-3">{{review.student.username}}</h5>
                      <p>{{review.student.profile.profession}}</p>
                      <p class="text-muted">
                        {{review.content}}
                      </p>
                    </div>
                  </div>
                  <ul class="list-unstyled d-flex justify-content-center text-warning mb-0">
                    {% with ''|center:review.rating as range %}
                    {% for i in range %}
                    <li><i class="fas fa-star fa-sm"></i></li>
                    {% endfor %}
                    {% endwith %}
                  </ul>
                </div>
            {% endif %}
          {% endfor %}
        <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleControls"
          data-mdb-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleControls"
          data-mdb-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>

        
        </div>
        {% else %}
          <div class="col-4">
            <p>No reviews available</p>
          </div>
        {% endif %}

    </div>
    </div>
  </div>
    <script type="text/javascript" src="{% static 'styles/js/mdb.min.js' %}"></script>
    <script type="text/javascript"></script>
    <script>
    function toggleReviewForm() {
        var reviewFormContainer = document.getElementById("reviewFormContainer");
        if (reviewFormContainer.style.display === "none") {
            reviewFormContainer.style.display = "block";
        } else {
            reviewFormContainer.style.display = "none";
        }
    }
    </script>
  </body>
</html>
{% endblock %}

course/templates/course/courses_table.html
{% extends 'main/loggedInPage.html' %}
{% block main_content %}
{% load static %}
    <head>
        <title>Course</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'styles/courses.table.css' %}" type="text/css">
    </head>

    <body>
        <h1 class="Course_list">My Courses</h1>
        <br><br>
        <div class="scroll">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>Course Name</th>
                        {% if user.profile.account_type == 'S'%}
                        <th>Teacher</th>
                        {% endif %}
                        <th>Price</th>
                        <th>Category</th>
                        {% if user.profile.account_type == 'T'%}
                        <th>Request</th>
                        {% endif %}
                    </tr>
                </thead>
                {% for course in courses %}
                <tbody>
                    <td><a href="/course/{{course.course_id}}">{{course.course_name.capitalize}}</td>
                    {% if user.profile.account_type == 'S'%}
                        <td><a href="#">{{course.teacher_id}}</td>
                    {% endif %}
                    <td>{{course.price}} ₪</td>
                    <td>{{course.get_category_display.capitalize}}</td>
                    {% if user.profile.account_type == 'T'%}
                    <td>{{course.get_pending_requset_count_for_course}}</td>
                    {% endif %}
                </tbody>
                {% endfor %}
            </table>
        </div>
        {% if user.profile.account_type == 'T'%}
        <a href="add">
            <button class="icon-btn add-btn">
                <div class="add-icon"></div>
                <div class="btn-txt">Add Course</div>
            </button>
        </a>
        {% endif %}
    </body>

{% endblock %}